# Generated by Django 3.2.7 on 2021-09-06 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('COM', 'Compulsory'), ('PRE', 'Prerequisite'), ('ELE', 'Elective'), ('REQ', 'Required')], default='COM', max_length=3)),
                ('course_title', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=10)),
                ('course_units', models.IntegerField(default=2)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='prequisites', to='coursesapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1L', '100 Level'), ('2L', '200 Level'), ('3L', '300 Level'), ('4L', '400 Level'), ('5L', '500 Level')], default='1L', max_length=2)),
                ('max_units', models.IntegerField(default=24)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursesapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterCourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('FIR', 'First'), ('SEC', 'Second'), ('SUM', 'Summer')], default='FIR', max_length=3)),
                ('course_list', models.ManyToManyField(blank=True, related_name='semester_courses', to='coursesapp.Course')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.studentclass')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_semester', models.CharField(choices=[('FIR', 'First'), ('SEC', 'Second'), ('SUM', 'Summer')], default='FIR', max_length=3)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursesapp.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coursesapp.profile')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('matric_no', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.studentclass')),
            ],
            bases=('coursesapp.profile',),
        ),
        migrations.CreateModel(
            name='LevelAdviser',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coursesapp.profile')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.department')),
            ],
            bases=('coursesapp.profile',),
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coursesapp.profile')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.department')),
            ],
            bases=('coursesapp.profile',),
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APR', 'Approved'), ('PEN', 'Pending'), ('UNA', 'Unapproved')], default='UNA', max_length=3)),
                ('academic_timeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.academictimeline')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursesapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursesapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.lecturer'),
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('grade', models.CharField(default='-', max_length=1)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.student')),
            ],
            options={
                'permissions': (('can_set_grade', 'Can Edit Course Grade'), ('can_view_grade', 'Can View Course Grade')),
                'unique_together': {('student', 'course')},
            },
        ),
    ]
