# Generated by Django 3.2.7 on 2021-09-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0002_portalopen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leveladviser',
            options={'permissions': [('is_adviser', 'User is a level adviser')]},
        ),
    ]
