# Generated by Django 3.2.7 on 2021-09-08 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0003_alter_leveladviser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.department'),
        ),
    ]
