# Generated by Django 3.2.7 on 2021-09-03 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coursesapp', '0004_studentclass_max_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coursesapp.profile')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('matric_no', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.department')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.studentclass')),
            ],
            bases=('coursesapp.profile',),
        ),
        migrations.CreateModel(
            name='LevelAdviser',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coursesapp.profile')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.department')),
            ],
            bases=('coursesapp.profile',),
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coursesapp.profile')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.department')),
            ],
            bases=('coursesapp.profile',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=10)),
                ('course_units', models.IntegerField(default=2)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='prequisites', to='coursesapp.Course')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.lecturer')),
            ],
        ),
    ]
