# Generated by Django 3.2.7 on 2021-09-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0004_alter_lecturer_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturer',
            options={'permissions': [('is_lecturer', 'User is a lecturer')]},
        ),
    ]
