# Generated by Django 3.2.7 on 2021-09-16 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0006_course_department'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='CourseRegistrationForm',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.student')),
        #         ('timeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.academictimeline')),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='courseregistration',
        #     name='form',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='coursesapp.courseregistrationform'),
        # ),
    ]
