# Generated by Django 3.2.7 on 2021-09-03 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0007_course_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterCourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('FIR', 'First'), ('SEC', 'Second'), ('SUM', 'Summer')], default='FIR', max_length=3)),
                ('course_list', models.ManyToManyField(blank=True, related_name='semester_courses', to='coursesapp.Course')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.studentclass')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APR', 'Approved'), ('PEN', 'Pending'), ('UNA', 'Unapproved')], default='UNA', max_length=3)),
                ('academic_timeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.academictimeline')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.student')),
            ],
            options={
                'permissions': (('can_approve', 'Approve course registration'), ('can_modify', 'Modify course registration')),
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('grade', models.CharField(default='-', max_length=1)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.student')),
            ],
            options={
                'permissions': (('can_set_grade', 'Can Edit Course Grade'), ('can_view_grade', 'Can View Course Grade')),
                'unique_together': {('student', 'course')},
            },
        ),
    ]
