# Generated by Django 3.2.7 on 2021-09-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0007_auto_20210916_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='coursesapp.Course'),
        ),
    ]
