# Generated by Django 3.2.7 on 2021-09-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0008_alter_course_prerequisites'),
        ('coursesapp', '0008_courseregistration_semestercourseallocation_studentgrade'),
    ]

    operations = [
    ]
