# Generated by Django 3.2.7 on 2021-09-27 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0016_auto_20210927_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingletonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='courseregistration',
            options={},
        ),
        migrations.AddField(
            model_name='student',
            name='promote_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursesapp.course'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursesapp.student'),
        ),
        migrations.AlterUniqueTogether(
            name='academictimeline',
            unique_together={('academic_semester', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together={('academic_timeline', 'student', 'course')},
        ),
        migrations.CreateModel(
            name='CourseRegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_current_units', models.IntegerField(default=0)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.student')),
                ('timeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursesapp.academictimeline')),
            ],
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='coursesapp.courseregistrationform'),
        ),
    ]
