# Generated by Django 3.2.7 on 2021-09-27 21:33

from django.db import migrations
from coursesapp.models import AcademicTimeline

def create_app_settings(apps, schema_editor):
    PortalOpen = apps.get_model("coursesapp", 'PortalOpen')

    # Create Initial data
    AcademicTimeline.create_first()
    p = PortalOpen.objects.create()
    p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0017_auto_20210927_2232'),
    ]

    operations = [
                migrations.RunPython(create_app_settings),
    ]
