# Generated by Django 3.2.7 on 2021-09-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicyear',
            old_name='session',
            new_name='year',
        ),
    ]
