# Generated by Django 3.2.7 on 2021-09-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0003_academictimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='max_units',
            field=models.IntegerField(default=24),
        ),
    ]
