# Generated by Django 3.2.7 on 2021-09-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0006_remove_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('COM', 'Compulsory'), ('PRE', 'Prerequisite'), ('ELE', 'Elective'), ('REQ', 'Required')], default='COM', max_length=3),
        ),
    ]
