# Generated by Django 3.2.7 on 2021-09-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0008_courseregistration_semestercourseallocation_studentgrade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseRegistration',
        ),
    ]
