# Generated by Django 3.2.7 on 2021-09-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0008_alter_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistrationform',
            name='total_current_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together={('academic_timeline', 'student', 'course')},
        ),
    ]
